### ISSUE TITLE
dependency to @jsbits/deep-clone

### ISSUE THREAD

**Issue by physikerwelt** [aMarCruz/pugjs-brunch#10]
I had to manually add @jsbits/deep-clone to my package.json file. 
I guess in 
https://github.com/aMarCruz/pugjs-brunch/commit/ca51f249d1251b0eb0529e80cacb31a8561aac31
the dependency should have been added as a real dependency not only as a dev-dependency. Does that make sense?

**Comment by aMarCruz** [comment]
@physikerwelt , fixed in v2.11.3
thanks!
