### ISSUE TITLE
wrong directory for includes?

### ISSUE THREAD

**Issue by DoumanAsh** [aMarCruz/pugjs-brunch#2]
Here is problem:
```
28 Dec 11:03:08 - error: Compiling of app/templates/index.pug failed. ENOENT: no such file or directory, open 'E:\Downloads\Git\js\lazy-tools\templates\_head.pug'
    at templates/index.pug line 1
```

My brunch config:
```
module.exports = {
    ....
    plugins: {
       ....
        pug: {
            staticBasedir: 'app/templates',
            preCompile: true
        }
    }
};
```

It seems for some reason pug is looking into wrong directory. (`app` is omitted for some reason?)

**UPD**: i suspect it might be because filename is passed as `templates/index.pug`. Not sure if it is not a pug bug.

**Comment by aMarCruz** [comment]
@DoumanAsh , seems the error is mine. I will fix this asap.

**Comment by aMarCruz** [comment]
@DoumanAsh please test the plugin version in the branch "dev". In your package.json:
```js
  ...
  "devDependencies": {
    "pugjs-brunch": "amarcruz/pugjs-brunch#dev",
```

This commit must fix the issue.
The README is updated and the plugin has a new option: `preCompilePattern` to limit precompilation.
I will release v2.8.6 soon, after make some testing (no time right now).

**Comment by DoumanAsh** [comment]
I verified: it works now.

**Comment by aMarCruz** [comment]
@DoumanAsh thanks, v2.8.6 is out!
