### ISSUE TITLE
Does pugjs-brunch work with auto-reload-brunch?

### ISSUE THREAD

**Issue by ooloth** [aMarCruz/pugjs-brunch#4]
Hi there,

I'm having trouble getting changes I make to pug files to trigger a browser auto reload.

When I start a new project ('brunch new'), the auto-reload-brunch plugin works fine. But, after installing pugjs-brunch ('npm install --save-dev pugjs-brunch') and adding an index.pug file to my app/assets/ folder, the auto-reloading stops.

The pugjs-brunch plugin updates the index.html version in the public folder, rather than the app/assets/ folder (no index.html is created in app/assets/). Is this the issue?

Do I need to place my pug files elsewhere, or perhaps add some pugjs settings to the brunch-config.js file?

Thanks in advance.

**Comment by hartreed** [comment]
Having the same issue. It's not that auto-reload or browser-sync stop: they still will apply changes to js or css, but they won't update any changes to pug files. I have to exit and restart the watcher before the new content will appear.

**Comment by pixelastic** [comment]
I found that forcing the reload to `true` in the `autoReload` plugin solved the issue for me:

```js
config: {
  plugins: {
    autoReload: {
      enabled: {
        css: true,
        js: true,
        assets: true
      }
    }
}
```

**Comment by hartreed** [comment]
@pixelastic this doesn't seem to work for me. Are you using browser-sync? Could I see your full brunch-config file?

I think part of the issue might be that my files are heavily modular, my index includes another pug file, which is itself made up of a bunch of mixins. I've already noticed that changing the mixins seems to provoke less of a response from the watcher (auto-reload/browser-sync) than editing one of the main includes.

**Comment by aMarCruz** [comment]
@ooloth ,
pugjs-brunch updates the index.html version in the public folder, this is the expected behavior as `brunch w -s` loads index.html from the public folder.

@hartreed ,
with pugjs-brunch you can use normal `require` in your templates. With this you gain code reduction because the child templates are not repeated elsewhere, and maybe this (with the @pixelastic tip) will solve some issues with auto-reload.

Example:
```jade
//- inner-tmpl.pug
p Hello #{userName}
```

and in your main template:
```jade
//- page1.pug
- var innerTmpl = require('./inner-tmpl.pug');
h1 Title
.content
  != innerTmpl({ userName: 'john' })
```

**Comment by abienz** [comment]
I've just got this issue too..

New project created with brunch new -s simple.

installed pugjs-brunch with --save-dev. and stylus-brunch

file is index.pug in assets folder /app/assets/index.pug

any changes to css or pug file don't autoreload both in Chrome and Firefox.

another project with pugjs-brunch 2.8 is ok however.

I tried the config settings suggested they don't fix the issue.

**Comment by pixelastic** [comment]
The workaround I posted earlier worked for me for a time. When I started including more and more pug files, brunch was able to understand there was a change, but did not trigger the live reload correctly.

In the end, I stopped using this plugin and did my own workaround:

```sh
#!/usr/bin/env sh
parallelshell \
  "onchange 'app/html/**/*.pug' -- pug ./app/html/index.pug -o ./app/assets/" \
  "brunch watch --server"
```

I basically put all my `pug` files in `app/html` (and exclude this directory from the directories watched by brunch). Whenever a file in there is changed, I run `pug` (from the `pug-cli` package) on the main entrypoint (which is an `index.pug` file in my case, incuding all the other `pug` files). The output is generated in `app/assets` which is in turn correctly handled by brunch livereload.

It's slower than a native solution, but it works.

**Comment by aMarCruz** [comment]
I have issues too with livereload and source maps after migrating to Brunch v2.10.* (pug and less) and can't find where the problem is :confused: ...

I hope [v2.11](https://github.com/brunch/brunch/pull/1664) will solve many issues like this one.

**Comment by pikeas** [comment]
Make sure you haven't forgotten to include `vendor.js` in your HTML page, that's where the client side logic for auto-refresh lives.

**Comment by ooloth** [comment]
Still seeing this issue...

It seems that pugjs-brunch does a good job updating the resulting .html files, but auto-reload-brunch doesn't notice because it's waiting to see changes in the app/assets folder (not the public folder) before triggering a browser update.

Would it help to output the resulting .html files to app/assets (instead of public)? All .pug changes (including changes to partials) will then trigger auto-reload-brunch (because it will notice the change to an .html file in app/assets) and the .html file in the public directory will be updated accordingly (without pugjs-brunch needing to do it).

Hopefully, changing the output folder from public to app/assets (or providing the option to do so) will be a simple fix to this issue.

**Comment by aMarCruz** [comment]
@ooloth , sorry by the delay.
The output location of compiled templates coming from the asset folder is not controlled by plugins, this is controlled by the user through the `paths.public` key of brunch-config so I can't provide a flag for this.

Regarding `auto-reload-brunch`, it has issues with mixins included in the .pug, but I can't reprocude the issue with my `app/assets/index.pug`. Any change, even without "cache-control:no-cache", is detected and launch a page refresh ...maybe using `watcher.usePolling: true` in your brunch-config helps.
`auto-reload-brunch` is an `onCompile` hook and care only about extensions, no paths.

The `compileStatic` method used by pugjs-brunch is very limited and a new API is WIP (See [brunch#1708](https://github.com/brunch/brunch/issues/1708)), hope this will have more capabilities.

By the way, with brunch v2.10.11 we have sourceMaps again :)
