### ISSUE TITLE
How to configure pug plugin in config file ?

### ISSUE THREAD

**Issue by sera2007** [aMarCruz/pugjs-brunch#5]
I'm using the code 

`module.exports = {
   ...
        templates: {
            joinTo: 'javascripts/app.js'
        },
    },`

` plugins: {
        pugjs: {
            staticBasedir: 'app/static_pug',
            staticPretty: true,
            compileDebug: true,
        },
....
`

But I don't get anything as result. I was trying to change joinTo param, but it didn't work for me. Do you have any thinking ?

**Comment by aMarCruz** [comment]
@sera2007  the property name is "pug".

Please see the [examples](https://github.com/aMarCruz/pugjs-brunch#examples).

**Comment by aMarCruz** [comment]
@sera2007 , I hope brunch/brunch#1691 solves your question.
Closing this issue now.
