### ISSUE TITLE
dependencies not working for static assets

### ISSUE THREAD

**Issue by buckle2000** [aMarCruz/pugjs-brunch#7]
The function `pug.compile` currently used for static assets does not return dependencies.

Please use `pug.compileClientWithDependenciesTracked` instead.

**Comment by aMarCruz** [comment]
@buckle2000 thanks, I'll review this issue asap.

**Comment by aMarCruz** [comment]
@buckle2000 you are right, `pug.compile` does not directly returns `dependencies`, but the function that `pug.compile` returns (`fn`) does contain it as a property. `fn` is passed to `_setDeps` in index.js#195.

This is not documented but still works on v2.0.0-rc.4 with this test:

```js
it('should output valid deps for assets', function (done) {
    const filename = 'app/assets/deps.pug'
    const content  = [
      'html',
      '  body',
      '    include footer.pug',
      ''
    ].join('\n')
    const expected = [
      sysPath.join('app', 'assets', 'footer.pug'),
    ]
    const plugin = new Plugin(brunchOpts)

    plugin.compileStatic({ data: content, path: filename }).then(function (data) {
      if (typeof data != 'string') data = data.data
      expect(data).toBeA('string')

      plugin.getDependencies(content, filename, function (error, dependencies) {
        expect(error).toNotExist()
        expect(dependencies + '').toBe(expected + '')
        done()
      })
    }).catch(done)
  })
```

Anyway, a future version of pugjs-brunch will use `compileClientWithDependenciesTracked` as you suggest.
Closing this issue now.
