### ISSUE TITLE
Incorrect getDependencies()

### ISSUE THREAD

**Issue by buckle2000** [aMarCruz/pugjs-brunch#9]
http://brunch.io/docs/plugins#method-getdependencies-file-array-path-
> Method: getDependencies(file): Array[Path]
> Given a file, this should return a list of file paths that depend on this one.

However, the current `getDependencies` returns "a list of file paths that this one depends on", not "a list of file paths that depend on this one".

**Comment by buckle2000** [comment]
Or is the description of `getDependencies` incorrect? For some reasons, this dependency system is still not working.

**Comment by buckle2000** [comment]
brunch never calls `getDependencies(any_template)`. It never asks for that information, so there is no way it can update dependents on update (in watch mode). It may be a design flaw of brunch.

**Comment by buckle2000** [comment]
So I fixed `getDependenies`, but the dependency system is still broken. 😕 😞

**Comment by aMarCruz** [comment]
@buckle2000 thanks for the feedback, I will investigate this.

**Comment by buckle2000** [comment]
There is something wrong with brunch itself. https://github.com/brunch/brunch/issues/1789

**Comment by aMarCruz** [comment]
yeah, recompiling dependencies with brunch is a nightmare :)

**Comment by aMarCruz** [comment]
@buckle2000 , pugjs-brunch v2.11.0 is in npm, I hope this version solves issues with the watcher.

Seems Brunch is [unmaintained now](https://github.com/brunch/brunch/pull/1664#issuecomment-407950555) and I don't know if I will update this plugin anymore.

Closing this.
